[tool.isort]
profile = "black"

[tool.black]
line-length = 120
include = '\.pyi?$'

[tool.pylint.messages_control]
max-line-length = 120
disable = [
    "no-member", # it cant find models object manager methods
    "missing-class-docstring",
    "missing-module-docstring",
    "missing-function-docstring",
    "line-too-long",
    "logging-fstring-interpolation", # Hate it, f-string really readable thing
    "broad-except", # really hard to know what type of exception could be
    "wrong-import-order", # black do it
    "fixme", # todos tree vscode plugin catch them
    "too-many-lines", # for django project models could be very long
    "too-few-public-methods", # not a big problem
    "unused-argument", # due nested functions it could happen
    "too-many-ancestors", # we use nested classes from django and drf, could happen
]