[tool.isort]
profile = "black"

[tool.black]
line-length = 120
include = '\.pyi?$'

[tool.pylint.messages_control]
max-line-length = 120
disable = [
    "no-member", # it cant find models object manager methods
    "missing-class-docstring",
    "missing-module-docstring",
    "missing-function-docstring",
    "line-too-long"
]