# Generated by Django 3.2.9 on 2021-11-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addrbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Название улицы', max_length=512, unique=True)),
                ('signes', models.ManyToManyField(blank=True, related_name='street_signes', to='addrbook.StreetSignes')),
            ],
            options={
                'verbose_name_plural': 'Улицы',
            },
        ),
    ]
