# Generated by Django 3.2.9 on 2021-11-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addrbook', '0002_streets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.PositiveIntegerField(help_text='Номер команды', unique=True)),
                ('name', models.CharField(default='', help_text='Название Команды', max_length=512, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Команды',
            },
        ),
    ]
