# Generated by Django 3.2.9 on 2021-11-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addrbook', '0003_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSignes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Название знака', max_length=512, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Индивидуальные указатели',
            },
        ),
    ]
