# Generated by Django 4.0.4 on 2023-04-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addrbook', '0004_customsignes'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='finished',
            field=models.BooleanField(blank=True, default=False, help_text='Команда финишировала'),
        ),
        migrations.AddField(
            model_name='teams',
            name='finished_date',
            field=models.DateTimeField(blank=True, help_text='Дата и время финиширования', null=True),
        ),
    ]
