# Generated by Django 3.2.9 on 2021-11-22 13:27

import administration.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20211122_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/home/art.antonov/mmb-pf/mmb_pf/media'), upload_to=administration.models.image_path)),
                ('app_name', models.CharField(help_text='Идентификатор приложения, которое загрузило файл', max_length=128)),
                ('desc', models.CharField(blank=True, default='', help_text='Описание', max_length=2048)),
            ],
            options={
                'verbose_name_plural': 'Хранилище изображений',
            },
        ),
    ]
