# Generated by Django 3.2.9 on 2021-11-27 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addrbook', '0003_teams'),
        ('administration', '0006_mmbpfusers_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmbpfusers',
            name='street',
            field=models.ForeignKey(blank=True, help_text='Улица', null=True, on_delete=django.db.models.deletion.SET_NULL, to='addrbook.streets'),
        ),
    ]
