# Generated by Django 3.2.9 on 2021-11-27 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addrbook', '0003_teams'),
        ('administration', '0007_mmbpfusers_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmbpfusers',
            name='sign',
            field=models.ForeignKey(blank=True, help_text='Уличный указатель', null=True, on_delete=django.db.models.deletion.SET_NULL, to='addrbook.streetsignes'),
        ),
    ]
