# Generated by Django 3.2.9 on 2021-12-04 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_mmbpfusers_custom_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantCardActionsJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания события')),
                ('ip', models.CharField(blank=True, default='', help_text='ip адрес с которого пришёл запрос', max_length=48)),
                ('user_agent', models.CharField(blank=True, default='', help_text='User agent котрый прислал браузер пользователя', max_length=1024)),
                ('username', models.CharField(default='', help_text='username пользователя вошедшего в систему', max_length=256)),
                ('user_id', models.IntegerField(default=None, help_text='id пользователя', validators=[django.core.validators.MinValueValidator(1)])),
                ('participant_id', models.IntegerField(default=None, help_text='id карточки участника', validators=[django.core.validators.MinValueValidator(1)])),
                ('desc', models.CharField(blank=True, default='', help_text='Описание действия', max_length=1024)),
            ],
        ),
    ]
