# Generated by Django 3.2.9 on 2021-12-04 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_participantcardactionsjournal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantcardactionsjournal',
            name='user_id',
            field=models.IntegerField(blank=True, default=None, help_text='id пользователя', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
