# Generated by Django 3.2.9 on 2021-12-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_alter_participantcardactionsjournal_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantcardactionsjournal',
            name='desc',
            field=models.CharField(blank=True, default='', help_text='Описание действия', max_length=4096),
        ),
    ]
